### ISSUE TITLE
Can not upload images

### ISSUE THREAD

**Issue by lesamarien** [aymhce/diasporadocker_ynh#11]
Hello

I installed my pod Diaspora under YunoHost with docker with this link: https://github.com/aymhce/diasporadocker_ynh 1

I am on YunoHost 3.0.1 with the Debian 9 distribution.

When I want to upload an image I have an internal server error and no image is downloaded. The folder Public/uploads/images is well configured with the diaspora account and write but it still does not work. I can write text but not upload images.

I tested with Firefox 60 under Ubuntu 18.04 and on IE 11 with Windows 7.

I encountered the same problem on debian 8.

I tested several tracks but without success:

I’m getting a 500 error page

Oh noes, you might have hit a bug in diaspora *! But this can also be caused by a setup problem, like an incorrectly setup custom landing page, an old Redis version or a database connectivity issue.

I did a tail -f log/production.log and here is the result:

[2018-06-20T21:05:34] INFO PID-352 TID-46970689171260 ActionController::Base: Parameters: {""=>“1529528734575”}
[2018-06-20T21:05:34] INFO PID-352 TID-46970689171260 ActionController::Base: Completed 200 OK in 116ms (Views: 40.3ms | ActiveRecord: 44.3ms)
[2018-06-20T21:05:36] INFO PID-352 TID-46970689171260 Rails: Started GET "/stream?max_time=1529452845&=1529528734576" for 172.18.0.1 at 2018-06-20 21:05:36 +0000
[2018-06-20T21:05:36] INFO PID-352 TID-46970689171260 ActionController::Base: Processing by StreamsController#multi as JSON
[2018-06-20T21:05:36] INFO PID-352 TID-46970689171260 ActionController::Base: Parameters: {“max_time”=>“1529452845”, “"=>“1529528734576”}
[2018-06-20T21:05:36] INFO PID-352 TID-46970689171260 ActionController::Base: Completed 200 OK in 53ms (Views: 0.6ms | ActiveRecord: 26.9ms)
[2018-06-20T21:05:37] INFO PID-352 TID-46970689171260 Rails: Started GET "/stream?max_time=1529452845&=1529528734577” for 172.18.0.1 at 2018-06-20 21:05:37 +0000
[2018-06-20T21:05:37] INFO PID-352 TID-46970689171260 ActionController::Base: Processing by StreamsController#multi as JSON
[2018-06-20T21:05:37] INFO PID-352 TID-46970689171260 ActionController::Base: Parameters: {“max_time”=>“1529452845”, “_”=>“1529528734577”}
[2018-06-20T21:05:37] INFO PID-352 TID-46970689171260 ActionController::Base: Completed 200 OK in 62ms (Views: 0.6ms | ActiveRecord: 36.3ms)
[2018-06-20T21:06:00] INFO PID-352 TID-46970689171260 Rails: Started POST “/photos” for 172.18.0.1 at 2018-06-20 21:06:00 +0000
[2018-06-20T21:06:00] INFO PID-352 TID-46970689171260 ActionController::Base: Processing by PhotosController#create as JSON
[2018-06-20T21:06:00] INFO PID-352 TID-46970689171260 ActionController::Base: Parameters: {“authenticity_token”=>“dRXE+LKagPPFOIi6WSwMcRIS7d0hbZsKrFvtZ37ed4aTHX147DQ5ToJfKCoz5tfufc8w+q88SFN4aBoEj5216Q==”, “photo”=>{“pending”=>“true”}, “qquuid”=>“c8931439-896a-4ba0-94ce-f74d6c4e4796”, “qqfilename”=>“ed833f4e6207f723.jpg”, “qqtotalfilesize”=>“4171”, “qqfile”=>#<ActionDispatch::Http::UploadedFile:0x00557075bd88d8 @tempfile=#Tempfile:/tmp/RackMultipart20180620-352-1d7sbwa.jpg, @original_filename=“ed833f4e6207f723.jpg”, @content_type=“image/jpeg”, @headers=“Content-Disposition: form-data; name=“qqfile”; filename=“ed833f4e6207f723.jpg”\r\nContent-Type: image/jpeg\r\n”>}
[2018-06-20T21:06:00] INFO PID-352 TID-46970689171260 ActionController::Base: Completed 500 Internal Server Error in 261ms (ActiveRecord: 2.6ms)
[2018-06-20T21:06:00] FATAL PID-352 TID-46970689171260 Rails:
[2018-06-20T21:06:00] FATAL PID-352 TID-46970689171260 Rails: NoMethodError (undefined method match' for nil:NilClass): [2018-06-20T21:06:00] FATAL PID-352 TID-46970689171260 Rails: [2018-06-20T21:06:00] FATAL PID-352 TID-46970689171260 Rails: app/models/photo.rb:101:inupdate_remote_path’
app/models/photo.rb:91:in diaspora_initialize' app/models/user.rb:235:inbuild_post’
app/controllers/photos_controller.rb:138:in legacy_create' app/controllers/photos_controller.rb:47:inblock in create’
app/controllers/photos_controller.rb:168:in rescuing_photo_errors' app/controllers/photos_controller.rb:46:increate’
[2018-06-20T21:06:39] INFO PID-349 TID-46970689171260 Rails: Started POST “/status_messages” for 172.18.0.1 at 2018-06-20 21:06:39 +0000
[2018-06-20T21:06:39] INFO PID-349 TID-46970689171260 ActionController::Base: Processing by StatusMessagesController#create as JSON
[2018-06-20T21:06:39] INFO PID-349 TID-46970689171260 ActionController::Base: Parameters: {“status_message”=>"[FILTERED]", “aspect_ids”=>“all_aspects”, “location_coords”=>"", “poll_question”=>"", “poll_answers”=>["", “”]}
[2018-06-20T21:06:40] INFO PID-349 TID-46970689171260 ActionController::Base: Completed 403 Forbidden in 532ms (Views: 1.9ms | ActiveRecord: 448.5ms)

**Comment by lesamarien** [comment]
Bonjour
Si ça peut vous aider voici les dernières lignes de production.log avec les erreurs : 

[2018-06-27T15:24:27] INFO  PID-341 TID-47110069374780 ActionController::Base: Processing by PeopleController#show as HTML
[2018-06-27T15:24:27] INFO  PID-341 TID-47110069374780 ActionController::Base:   Parameters: {"id"=>"8efad6805c2c01363f4f0242ac120004"}
[2018-06-27T15:24:27] INFO  PID-341 TID-47110069374780 ActionController::Base: Completed 200 OK in 639ms (Views: 368.9ms | ActiveRecord: 125.1ms)
[2018-06-27T15:24:28] INFO  PID-341 TID-47110069374780 Rails: Started GET "/notifications?per_page=10&page=1&_=1530106028393" for 195.221.156.31 at 2018-06-27 $
[2018-06-27T15:24:28] INFO  PID-341 TID-47110069374780 ActionController::Base: Processing by NotificationsController#index as JSON
[2018-06-27T15:24:28] INFO  PID-341 TID-47110069374780 ActionController::Base:   Parameters: {"per_page"=>"10", "page"=>"1", "_"=>"1530106028393"}
[2018-06-27T15:24:28] INFO  PID-341 TID-47110069374780 ActionController::Base: Completed 200 OK in 36ms (Views: 1.3ms | ActiveRecord: 9.2ms)
[2018-06-27T15:24:28] INFO  PID-338 TID-47110069374780 Rails: Started GET "/people/8efad6805c2c01363f4f0242ac120004/stream?_=1530106028394" for 195.221.156.31 $
[2018-06-27T15:24:28] INFO  PID-338 TID-47110069374780 ActionController::Base: Processing by PeopleController#stream as JSON
[2018-06-27T15:24:28] INFO  PID-338 TID-47110069374780 ActionController::Base:   Parameters: {"_"=>"1530106028394", "person_id"=>"8efad6805c2c01363f4f0242ac120$
[2018-06-27T15:24:28] INFO  PID-338 TID-47110069374780 ActionController::Base: Completed 200 OK in 35ms (Views: 1.5ms | ActiveRecord: 4.7ms)
[2018-06-27T15:24:29] INFO  PID-338 TID-47110069374780 Rails: Started GET "/profile/edit" for 195.221.156.31 at 2018-06-27 15:24:29 +0200
[2018-06-27T15:24:29] INFO  PID-338 TID-47110069374780 ActionController::Base: Processing by ProfilesController#edit as HTML
[2018-06-27T15:24:30] INFO  PID-338 TID-47110069374780 ActionController::Base: Completed 200 OK in 335ms (Views: 296.1ms | ActiveRecord: 9.8ms)
[2018-06-27T15:24:30] INFO  PID-341 TID-47110069374780 Rails: Started GET "/notifications?per_page=10&page=1&_=1530106030699" for 195.221.156.31 at 2018-06-27 $
[2018-06-27T15:24:30] INFO  PID-341 TID-47110069374780 ActionController::Base: Processing by NotificationsController#index as JSON
[2018-06-27T15:24:30] INFO  PID-341 TID-47110069374780 ActionController::Base:   Parameters: {"per_page"=>"10", "page"=>"1", "_"=>"1530106030699"}
[2018-06-27T15:24:30] INFO  PID-341 TID-47110069374780 ActionController::Base: Completed 200 OK in 36ms (Views: 0.7ms | ActiveRecord: 8.7ms)
[2018-06-27T15:24:34] INFO  PID-341 TID-47110069374780 Rails: Started POST "/photos" for 195.221.156.31 at 2018-06-27 15:24:34 +0200
[2018-06-27T15:24:34] INFO  PID-341 TID-47110069374780 ActionController::Base: Processing by PhotosController#create as JSON
[2018-06-27T15:24:34] INFO  PID-341 TID-47110069374780 ActionController::Base:   Parameters: {"authenticity_token"=>"a22ESUipmjC3h5hMPdGc7JtGL1q9HRx8PvD7t4C9Sg$
[2018-06-27T15:24:35] INFO  PID-341 TID-47110069374780 ActionController::Base: Completed 500 Internal Server Error in 694ms (ActiveRecord: 17.1ms)
[2018-06-27T15:24:35] FATAL PID-341 TID-47110069374780 Rails:
[2018-06-27T15:24:35] FATAL PID-341 TID-47110069374780 Rails: NoMethodError (undefined method `match' for nil:NilClass):
[2018-06-27T15:24:35] FATAL PID-341 TID-47110069374780 Rails:
[2018-06-27T15:24:35] FATAL PID-341 TID-47110069374780 Rails: app/models/photo.rb:101:in `update_remote_path'
app/models/photo.rb:91:in `diaspora_initialize'
app/models/user.rb:235:in `build_post'
app/controllers/photos_controller.rb:138:in `legacy_create'
app/controllers/photos_controller.rb:47:in `block in create'
app/controllers/photos_controller.rb:168:in `rescuing_photo_errors'
app/controllers/photos_controller.rb:46:in `create'
[2018-06-27T15:28:06] INFO  PID-338 TID-47110069374780 Rails: Started GET "/notifications?per_page=10&page=1&_=1530101746821" for 195.221.156.31 at 2018-06-27 $
[2018-06-27T15:28:06] INFO  PID-338 TID-47110069374780 ActionController::Base: Processing by NotificationsController#index as JSON
[2018-06-27T15:28:06] INFO  PID-338 TID-47110069374780 ActionController::Base:   Parameters: {"per_page"=>"10", "page"=>"1", "_"=>"1530101746821"}
[2018-06-27T15:28:06] INFO  PID-338 TID-47110069374780 ActionController::Base: Completed 200 OK in 149ms (Views: 1.7ms | ActiveRecord: 22.2ms)

Je vois dans le log des erreurs avec Rails. est-ce que cela vient de là le problème ?
Là je suis un peu perdu.

**Comment by lesamarien** [comment]
Bonjour

Avec la mise à jour vers la version 0.7.7.1, le souci avec les images a été corrigé.
